#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kyotocabinet
Version  : 1.2.79
Release  : 4
URL      : https://fallabs.com/kyotocabinet/pkg/kyotocabinet-1.2.79.tar.gz
Source0  : https://fallabs.com/kyotocabinet/pkg/kyotocabinet-1.2.79.tar.gz
Summary  : a straightforward implementation of DBM
Group    : Development/Tools
License  : GPL-3.0
Requires: kyotocabinet-bin = %{version}-%{release}
Requires: kyotocabinet-lib = %{version}-%{release}
Requires: kyotocabinet-license = %{version}-%{release}
Requires: kyotocabinet-man = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : gettext-bin
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(zlib)
Patch1: 0001-Disable-march-native.patch

%description
================================================================
Kyoto Cabinet: a straightforward implementation of DBM
================================================================

%package bin
Summary: bin components for the kyotocabinet package.
Group: Binaries
Requires: kyotocabinet-license = %{version}-%{release}

%description bin
bin components for the kyotocabinet package.


%package dev
Summary: dev components for the kyotocabinet package.
Group: Development
Requires: kyotocabinet-lib = %{version}-%{release}
Requires: kyotocabinet-bin = %{version}-%{release}
Provides: kyotocabinet-devel = %{version}-%{release}
Requires: kyotocabinet = %{version}-%{release}

%description dev
dev components for the kyotocabinet package.


%package doc
Summary: doc components for the kyotocabinet package.
Group: Documentation
Requires: kyotocabinet-man = %{version}-%{release}

%description doc
doc components for the kyotocabinet package.


%package lib
Summary: lib components for the kyotocabinet package.
Group: Libraries
Requires: kyotocabinet-license = %{version}-%{release}

%description lib
lib components for the kyotocabinet package.


%package license
Summary: license components for the kyotocabinet package.
Group: Default

%description license
license components for the kyotocabinet package.


%package man
Summary: man components for the kyotocabinet package.
Group: Default

%description man
man components for the kyotocabinet package.


%prep
%setup -q -n kyotocabinet-1.2.79
cd %{_builddir}/kyotocabinet-1.2.79
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1614896928
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%reconfigure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1614896928
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kyotocabinet
cp %{_builddir}/kyotocabinet-1.2.79/COPYING %{buildroot}/usr/share/package-licenses/kyotocabinet/8624bcdae55baeef00cd11d5dfcfa60f68710a02
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kccachetest
/usr/bin/kcdirmgr
/usr/bin/kcdirtest
/usr/bin/kcforestmgr
/usr/bin/kcforesttest
/usr/bin/kcgrasstest
/usr/bin/kchashmgr
/usr/bin/kchashtest
/usr/bin/kclangctest
/usr/bin/kcpolymgr
/usr/bin/kcpolytest
/usr/bin/kcprototest
/usr/bin/kcstashtest
/usr/bin/kctreemgr
/usr/bin/kctreetest
/usr/bin/kcutilmgr
/usr/bin/kcutiltest

%files dev
%defattr(-,root,root,-)
/usr/include/kccachedb.h
/usr/include/kccommon.h
/usr/include/kccompare.h
/usr/include/kccompress.h
/usr/include/kcdb.h
/usr/include/kcdbext.h
/usr/include/kcdirdb.h
/usr/include/kcfile.h
/usr/include/kchashdb.h
/usr/include/kclangc.h
/usr/include/kcmap.h
/usr/include/kcplantdb.h
/usr/include/kcpolydb.h
/usr/include/kcprotodb.h
/usr/include/kcregex.h
/usr/include/kcstashdb.h
/usr/include/kctextdb.h
/usr/include/kcthread.h
/usr/include/kcutil.h
/usr/lib64/libkyotocabinet.so
/usr/lib64/pkgconfig/kyotocabinet.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/kyotocabinet/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libkyotocabinet.so.16
/usr/lib64/libkyotocabinet.so.16.14.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kyotocabinet/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/kccachetest.1
/usr/share/man/man1/kcdirmgr.1
/usr/share/man/man1/kcdirtest.1
/usr/share/man/man1/kcforestmgr.1
/usr/share/man/man1/kcforesttest.1
/usr/share/man/man1/kcgrasstest.1
/usr/share/man/man1/kchashmgr.1
/usr/share/man/man1/kchashtest.1
/usr/share/man/man1/kclangctest.1
/usr/share/man/man1/kcpolymgr.1
/usr/share/man/man1/kcpolytest.1
/usr/share/man/man1/kcprototest.1
/usr/share/man/man1/kcstashtest.1
/usr/share/man/man1/kctreemgr.1
/usr/share/man/man1/kctreetest.1
/usr/share/man/man1/kcutilmgr.1
/usr/share/man/man1/kcutiltest.1
